# Job/Submission settings
dump_dir: "jobs/"
job_name: "llama-3.2-tiny"
num_nodes: 32
partition: "standard-g"
account: "project_465001265"
time: "0-01:00:00"
container: "/appl/local/containers/sif-images/lumi-rocm-rocm-6.2.2.sif"
load_config: null

# Training settings
max_grad_norm: 2.0
gc_freq: 4
data_parallel_shard_degree: 8
data_parallel_replicate_degree: 32
tensor_parallel_degree: 1
train_batch_size: 2
train_num_steps: 22000
compile: true
enable_loss_parallel: true
enable_cut_cross_entropy: true
init_timeout_seconds: 300
train_timeout_seconds: 100

# Datasets (nested)
dataset:
  data_logical_shards: 8192
  data_dirs: # scratch/project_465001265/rasmus/datamix/rasmus/gemma3/data
    - "../../rasmus/datamix/rasmus/gemma3/data/train_code_github_common/"
    - "../../rasmus/datamix/rasmus/gemma3/data/train_dan_books_dynaword/"
    - "../../rasmus/datamix/rasmus/gemma3/data/train_dan_books_fineweb2/"
    - "../../rasmus/datamix/rasmus/gemma3/data/train_dan_books_hplt2/"
    - "../../rasmus/datamix/rasmus/gemma3/data/train_dan_conversation_dynaword/"
    - "../../rasmus/datamix/rasmus/gemma3/data/train_dan_dialect_dynaword/"
    - "../../rasmus/datamix/rasmus/gemma3/data/train_dan_legal_dynaword/"
    - "../../rasmus/datamix/rasmus/gemma3/data/train_dan_news_dynaword/"
    - "../../rasmus/datamix/rasmus/gemma3/data/train_dan_news_fineweb2/"
    - "../../rasmus/datamix/rasmus/gemma3/data/train_dan_news_hplt2/"
    - "../../rasmus/datamix/rasmus/gemma3/data/train_dan_other_dynaword/"
    - "../../rasmus/datamix/rasmus/gemma3/data/train_dan_other_fineweb2/"
    - "../../rasmus/datamix/rasmus/gemma3/data/train_dan_other_hplt2/"
    - "../../rasmus/datamix/rasmus/gemma3/data/train_dan_read_dynaword/"
    - "../../rasmus/datamix/rasmus/gemma3/data/train_dan_social_dynaword/"
    - "../../rasmus/datamix/rasmus/gemma3/data/train_dan_social_fineweb2/"
    - "../../rasmus/datamix/rasmus/gemma3/data/train_dan_social_hplt2/"
    - "../../rasmus/datamix/rasmus/gemma3/data/train_dan_web_dynaword/"
    - "../../rasmus/datamix/rasmus/gemma3/data/train_dan_web_fineweb2/"
    - "../../rasmus/datamix/rasmus/gemma3/data/train_dan_web_hplt2/"
    - "../../rasmus/datamix/rasmus/gemma3/data/train_dan_wiki_dynaword/"
    - "../../rasmus/datamix/rasmus/gemma3/data/train_dan_wiki_fineweb2/"
    - "../../rasmus/datamix/rasmus/gemma3/data/train_dan_wiki_hplt2/"
    - "../../rasmus/datamix/rasmus/gemma3/data/train_en_books_common/"
    - "../../rasmus/datamix/rasmus/gemma3/data/train_en_legal_common/"
    - "../../rasmus/datamix/rasmus/gemma3/data/train_en_news_common/"
    - "../../rasmus/datamix/rasmus/gemma3/data/train_en_other_common/"
    - "../../rasmus/datamix/rasmus/gemma3/data/train_en_science_common/"
    - "../../rasmus/datamix/rasmus/gemma3/data/train_en_wiki_common/"
    - "../../rasmus/datamix/rasmus/gemma3/data/train_mul_legal_dynaword/"
    - "../../rasmus/datamix/rasmus/gemma3/data/train_mul_par_opus/"
  dataset_weights: "0,0,0,0,0,0,0,0,0.0136,0,0,0,0.222,0,0,0.0256,0,0,0.0012,0.4424,0,0,0,0,0.0726,0.0584,0.1542,0,0,0,0.01"
  bos_token: 128000
  eos_token: 128001
  drop_tokens: ""

tokenizer_name: "meta-llama/Llama-3.2-3B"

# Logging & metrics
log_freq: 10
log_rank0_only: true
save_tb_folder: "tb"
enable_tensorboard: false
enable_wandb: true
wandb_entity: "gbar-university-of-southern-denmark"
wandb_project: "llama-3.2-tiny"

# Checkpointing
enable_checkpoint: true
checkpoint_folder: "checkpoints"
checkpoint_interval: 2000
model_weights_only: true
export_dtype: "bfloat16"
forced_load_path: null

# Model
model_name: "llama3"
flavor: "tiny"
seq_len: 8192
norm_type: "compiled_rmsnorm"

# Mup
enable_mup: false
base_model_width: 512
model_width: 4096
mup_input_alpha: 1.0
mup_output_alpha: 1.0
mup_log_coord_check: false

# Optimizer
opt_class: "torch.optim.AdamW"
opt_cfg:
  lr: 0.0003
  betas: [0.9, 0.95]
  weight_decay: 0.1
  eps: 1e-8
  fused: true

# LR Schedule
scheduler: "linear_warmup_cosine"
warmup_steps: 50

# FSDP
mixed_precision_param: "bfloat16"
mixed_precision_reduce: "float32"

# Activation checkpointing and experimental
ac_mode: "none"
selective_ac_option: "op"
enable_async_tensor_parallel: false
enable_compiled_autograd: true

# Profiling
enable_profiling: false
enable_memory_snapshot: false
traces_folder: "traces"
memory_snapshot_folder: "snapshots"
profile_freq: 10