[project]
name = "maester"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Rasmus Larsen", email = "rasmus.larsen@alexandra.dk" }
]
dependencies = []
readme = "README.md"
requires-python = ">= 3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/maester"]